imi-frankfurt/dataelementhub.model

src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/MemberHandler.java
src/main/java/de/dataelementhub/model/service/ElementService.java

* Add methods to enable updating dataElementGroup and record members.
* See [REST PR](https://github.com/mig-frankfurt/dataelementhub.rest/pull/27)

#17 - Update dataElementGroup members

---

CHANGELOG.md
src/main/java/de/dataelementhub/model/dto/element/ElementPath.java
src/main/java/de/dataelementhub/model/dto/listviews/SimplifiedElementIdentification.java
src/main/java/de/dataelementhub/model/handler/element/ElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/ElementPathHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/DefinitionHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
src/main/java/de/dataelementhub/model/service/ElementService.java

* Add ElementPathHandler
* Add method to return all available paths for a given element
* See [#37](https://github.com/mig-frankfurt/dataelementhub.rest/pull/37)

#23 - Add endpoint to return element path

---

pom.xml
src/main/resources/schema/dehubElementValidation.json

* Expand the enumeratedValueDomain validation
* See [#25](https://github.com/mig-frankfurt/dataelementhub.model/issues/25)

#25 - EnumeratedValueDomain should validate all permittedValues before saving them

---

src/main/java/de/dataelementhub/model/dto/export/ExportInfo.java
src/main/java/de/dataelementhub/model/handler/export/ExportHandler.java
src/main/java/de/dataelementhub/model/service/ExportService.java

* a bit of housekeeping. using constants, combining methods...
* requires change in dehub.rest (see latest changes in [dehub.rest #30](https://github.com/mig-frankfurt/dataelementhub.rest/pull/30)

#33 - Change export Format type

---

src/main/java/de/dataelementhub/model/handler/importhandler/ImportHandler.java
src/main/java/de/dataelementhub/model/service/ImportService.java

*  Import validation against schema is not asynchronous anymore
* Check if the import endpoint deliver instant feedback if the imported file is not valid
Test with [#48](https://github.com/mig-frankfurt/dataelementhub.rest/pull/48)

#36 -Make import validation synchronous

---

src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValuesHandler.java

* before importing a value domain into another namespace, check if it already was imported
* same for permitted values
* Check if error from bug report is fixed

#32 - Importing the same valueDomain twice leads to internal server error

---

src/main/java/de/dataelementhub/model/handler/element/ElementPathHandler.java
src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java

* Non-logged-in users are now able to call the paths of public elements
* Check if these descibed paths can be called without logging in

#44 - enable calling path for public elements without login

---

src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
src/main/java/de/dataelementhub/model/service/ElementService.java

* Reading elements from hidden namespaces no longer works for unauthorized users
* See #51 and check if this is fixed

#51 unauthorized access to elements in hidden namespaces must be denied

---

src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java

* remove identification from permitted values before inserting as part of value domain
* see the issue description and check if the undesired behaviour is gone

#53 - Do not keep identification for permitted values when creating a value domain

---

src/main/java/de/dataelementhub/model/handler/element/ElementHandler.java

* When importing an enumerated value domain to another namespace, also include the permitted values
* See the issue description and check if the problem is gone

#54 - Importing enumerated value domain does not import permitted values

---

src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java

* Bugfix [#61](https://github.com/mig-frankfurt/dataelementhub.model/issues/61)
* Check if the desicribed problem in [#61](https://github.com/mig-frankfurt/dataelementhub.model/issues/61) is solved

#61 - Namespace members are not returned after updating the namespace

---

src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/validation/PermittedValueHandler.java
src/main/java/de/dataelementhub/model/service/ElementService.java

* Enable releasing elements using update controller
* Check if releasing and updating an element at the same time works as expected

#65 - Enable releasing elements using update controller

---

src/main/java/de/dataelementhub/model/service/SearchService.java

* Enable searching for namespaces.
* Create a namespace and search for its designation.

#67 - Search function is not working for namespaces

---

src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/MemberHandler.java

* When updating a draft, keep the related scoped identifier hierarchy entries
* close #78 
* check if the error from the issue description is gone (please check for dataelements, dataelementgroups and records)

#78 - Updating drafts is not working properly

---

src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
src/main/java/de/dataelementhub/model/service/ElementService.java
src/main/java/de/dataelementhub/model/service/NamespaceService.java

* Check if the associated value domain is released before releasing a data element and throw an IllegalStateException if it is not the case.
* Check if the described problem [#85](https://github.com/mig-frankfurt/dataelementhub.model/issues/85) is solved.

#85 - Released valueDomain is a requirement for releasing a dataElement

---

src/main/java/de/dataelementhub/model/handler/element/DataElementGroupHandler.java
src/main/java/de/dataelementhub/model/handler/element/ElementHandler.java
src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/IdentificationHandler.java
src/main/java/de/dataelementhub/model/handler/element/section/ValueDomainHandler.java

* Remove the element type staged.
* Check if the related enpoints still working.

#87 - Remove the element type staged

---

CHANGELOG.md
src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java

* Move check for value domain status to the beginning of the dataelement update method
* close #93
* See #93 and check if problem is solved

#93 - Trying to release an element with draft value domain does not fail correctly

---

src/main/java/de/dataelementhub/model/handler/element/RecordHandler.java

* Allow updating members for DRAFT records.
* Check if the associated issue is solved.

#98 - Updating record members returns 422 Unprocessable Entity

---

src/main/java/de/dataelementhub/model/handler/element/DataElementHandler.java

* When creating released dataelements with value domain urn, check if the status of the value domain fits.
* see #103 and check if problem is gone

#103 - Creating released dataelements with draft value domain should fail

---

pom.xml
src/main/java/de/dataelementhub/model/handler/element/NamespaceHandler.java
src/main/java/de/dataelementhub/model/service/SearchService.java

* catch NoSuchElementException when searching in namespaces, fixing an error in search when there are hidden namespaces
* close #105 
* check if problem from #105 is gone

#105 - Error in search

---

src/main/java/de/dataelementhub/model/handler/importhandler/StagedElementHandler.java

* check if the imported element is already converted
* close #107 
* follow the described steps in #107

#107 - Import - already converted valueDomains are not recognized
